feat: 로드맵 페이지 구현
woowacourse/prolog pull request #1097
Opened 2022-10-24 06:58 UTC by euijinkk

## 로드맵 페이지 구현
백엔드가 나중에 나올 예정이라, 일단 msw 기반으로 구현했습니다.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/24906022/197465374-07f5545d-c771-483a-8958-b893d3cb3401.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/24906022/197465419-791aebe8-a5e2-4778-9a07-14f054d57062.png">

`/roadmap`으로 가셔서 UI 확인하시면 됩니다.

내년에 로드맵 기능이 커질 것 같아요.
5기가 이어받을 것 같아서 깔끔하게 코드 짜놓는게 중요할거같아요.
코드단에서 자유로운 피드백 부탁드립니다.

conflict는 리뷰 후 local에서 제거한후 올리겠습니다.

2022-10-27 01:03 UTC, al-bur requested changes
안녕하세요 시지프, 마르코~
코드 깔끔하게 잘 작성해주셨네요!! query를 hook으로 추출해서 하니, 컴포넌트의 가독성이 많이 좋다고 느꼈습니다~ 코드리뷰하는 사람 입장에서는, api 요청을 어떻게 하고, 이를 어떻게 불러오는 지 알 필요가 없어서 좋네요

코멘트 확인해주세요!

2022-10-31 01:39 UTC, wonsss commented on frontend/public/index.html
> +    <div id="overlay-root"></div>
쌓임 맥락의 순서를 정적으로 보장하기 위해서 이렇게 root의 형제 요소로 portal 이 사용하는 요소들을 배치하였습니다.
혹시 앨버 생각에는 어떻게 수정하면 좋을지 꿀팁을 알려주시면 감사하겠습니다.

2022-10-31 01:46 UTC, euijinkk commented on frontend/public/index.html
> +    <div id="overlay-root"></div>
의견을 덧붙이자면!!

아래 3가지 방법이 있을 것 같아요.

1. root 의 형제로 여러개 배치했을 때 
2. root 의 형제로 portal 한개만 배치했을 때
3. root 안에 넣었을 때

2,3 번의 경우, 쌓임맥락이 동적으로 생성되어서 제어가 힘들 것같아요.
1번 방식으로 해야 쌓임맥락을 통제할 수 있을 것 같아요.

앨버 생각이 궁금합니다!

2022-10-31 01:59 UTC, euijinkk commented on frontend/src/apis/keywords.ts
> +  keywordId: number;
좋아요! 근데 저 3가지 타입이 지금 현재 우연히 같다는 생각이 들어서, 명시적으로 구분하면 좋을 것 같아요. 
재사용 하면서도, 명시적으로 분리하여 확장 가능성을 열어두고자 아래처럼 짜보았는데 어떤가요?

[refactor: sessionId와 keywordId 관련타입 선언](https://github.com/woowacourse/prolog/pull/1097/commits/47b470abed38fe0b7fcdbcf69c2b431dd73a4c30)

2022-10-31 02:00 UTC, euijinkk commented on frontend/src/components/@shared/SideSheet/SideSheet.tsx
> +  handleCloseSideSheet,
오오 좋은 리뷰 감사합니다! 좋은 관점인것같아요~

[refactor: on-prefix를 사용해서 onClickBackdrop이라고 네이밍을 범용성 있게 수정](https://github.com/woowacourse/prolog/pull/1097/commits/2a363d8e5db1ce5de13a91c54a5673ac1f29f5d4)

2022-10-31 02:02 UTC, euijinkk commented on frontend/src/components/Button/ResponsiveButton.tsx
> +}
아하 그렇네요. 저는 interface로 썼고, 마르코는 type으로써서 차이가 발생한 것 같아요. 
프로젝트 전체적으로 type, interface가 섞여있는 것 같네요. 
추후 문서화 팀이랑 같이 논의해서 결정하고 통일하면 어떨까요?

2022-10-31 02:06 UTC, euijinkk commented on frontend/src/components/LabelledImage/LabelledImage.tsx
> +import React, { ImgHTMLAttributes } from 'react';
제거했습니당!! 감사합니다!

2022-10-31 02:12 UTC, euijinkk commented on frontend/src/components/TopKeywordList/TopKeywordList.tsx
> +          {index + 1 !== topKeywordList?.length && <StyledArrow />}
오오 맞아요. 지금 보니 정말 잘 안 읽히네요.

변수 분리 해주었습니다!

[refactor: 가독성을 위해 isNotLast 변수 분리](https://github.com/woowacourse/prolog/pull/1097/commits/a31504a718db6ed28af0d7ecd78c09a4fb8c3672)

2022-10-31 02:16 UTC, wonsss reviewed
앨버 리뷰 감사합니다. 댓글 달았어요! 다시 확인 부탁드려요

2022-10-31 02:16 UTC, wonsss commented on frontend/src/components/Button/ResponsiveButton.tsx
> +    <StyledResponsiveButton
해당 부분은 스타일 파일 분리를 하지 않았었네요. 분리하여 스타일드 컴포넌트는 내부에서 별도의 이름을 갖도록 수정했어요

2022-10-31 02:16 UTC, wonsss commented on frontend/src/components/TopKeywordList/TopKeywordList.tsx
> +      {topKeywordList?.map((keyword, index) => (
맞아요. 통일해주면 좋을 것 같아요.
다만, 여기서는 keyword를 사용할 필요가 있어서 의도적으로 구조분해할당을 하지 않았습니다.

2022-10-31 02:16 UTC, wonsss commented on frontend/src/components/KeywordDetailSideSheet/KeywordDetailSideSheet.tsx
> +  handleCloseSideSheet: () => void;
컨벤션 통일하는 게 좋겠네요. `  handleCloseSideSheet: () => void;` 이런 식으로 수정하겠습니다.

2022-10-31 02:16 UTC, wonsss commented on frontend/src/components/KeywordDetailSideSheet/KeywordDetailSideSheet.tsx
> +  const { quizList } = useGetQuizListByKeyword({ sessionId, keywordId });
감사합니다.

2022-10-31 02:16 UTC, wonsss commented on frontend/src/components/KeywordList/KeywordList.tsx
> +        onClick={() => handleClickKeyword(selectedTopKeyword)}
저희는 이렇게 해도 가독성 등 면에서 무난한 것 같아서 적용했습니다. 앨버가 생각하는 더 나은 방법이 있으면 공유 부탁드려요.

2022-10-31 10:00 UTC, al-bur commented on frontend/public/index.html
> +    <div id="overlay-root"></div>
쌓임 맥락의 순서를 정적으로 보장하기 위한 것이였군요!! 이거는 제가 해보지 않아서 궁금해서 질문 남겼던 거에요~
음, 제가 이해한 바를 말해보면, 이렇게 두 개의 `div` 요소들을 배치해주면서 무조건 backdrop이 overlay보다 먼저 쌓일 수 있도록 한다는 건가요? 
동적으로 컨트롤한다면 쌓임 맥락의 순서를 무조건 고정 시켜줘야하니까 신경도 많이 써야하고요!!

2022-10-31 10:01 UTC, al-bur commented on frontend/src/apis/keywords.ts
> +  keywordId: number;
그렇네요. 우연히 같을 수도 있다는 생각은 못했네요.
Request로 나눠준 것 좋은 것 같아요~

2022-10-31 10:02 UTC, al-bur commented on frontend/src/components/Button/ResponsiveButton.tsx
> +}
좋습니다~

2022-10-31 10:08 UTC, al-bur commented on frontend/src/components/KeywordList/KeywordList.tsx
> +        onClick={() => handleClickKeyword(selectedTopKeyword)}
사실, 이 부분도 컨벤션으로 정해놓으면 좋겠다라는 생각이 들었어요!

1. 익명함수를 전달할 수도 있고,
2. 기명함수를 선언해서 전달해줄 수도 있을 겁니다.

익명함수로 하게 되면, 정확히 해당 함수가 어떠한 역할을 할 지 잘 모를 수도 있다고 생각을 했었습니다.
근데, 지금 같은 상황에서는 괜찮을 것 같네요!!

2022-10-31 10:09 UTC, al-bur approved these changes
두 분 고생하셨습니다~ㅎㅎㅎ

2022-11-18 02:26 UTC, JUDONGHYEOK approved these changes
와우 시,마 수고했어요!! 역시 믿고보는 시마네요 개인적으로 궁금한 부분 코멘트 남겨놨으니 자유롭게 확인하시고 답변 남겨주시면 감사하겠습니다!!

2022-12-04 12:25 UTC, euijinkk commented on frontend/src/components/@shared/SideSheet/SideSheet.style.ts
> +  ${({ width }) => css`
저는 상황에 따라 두개를 자유롭게 쓰는 편입니다.
컨벤션 정해지면 통일하면 좋을거같네요~~

2022-12-04 12:29 UTC, euijinkk commented on frontend/src/components/KeywordList/KeywordList.tsx
> +/** @jsxImportSource @emotion/react */
css prop 을 사용하기 위한 설정인데요.
babel 설정이 전체적으로 한번 필요할 것 같아요..!

2022-12-04 12:30 UTC, euijinkk commented on frontend/src/components/TopKeywordList/TopKeywordList.tsx
> +              alt=""
이미 text를 받고 있기 때문에, alt가 필요없는 상황이라고 생각하여 넣지 않았습니다~!

2022-12-04 12:32 UTC, merged