feat: 로드맵 키워드 구현
woowacourse/prolog pull request #1098
Opened 2022-10-24 17:20 UTC by wishoon

## 구현 사항
- [x] 키워드 생성
- [x] 키워드 삭제
- [x] 키워드 수정
- [x] 키워드 단건 조회
- [x] 세션에 속한 최상위 키워드 목록 조회
- [x] 최상위 키워드에 속한 모든 자식 키워드 목록 조회

## 전달 사항
* DB migration은 #1088 에서 수달이 진행해주셔서 따로 하지 않았습니다.
* NewDocumentTest 기반으로 문서 테스트 작성했습니다.
* a7918b1 에 대해서 개선 의견을 받고 싶습니다.
  * 현재는 **키워드 계층의 갯수 + 1** 만큼 조회 쿼리가 발생 하고 있습니다.. JPA 상에서 더 최적화를 할 수 있을지 고민인데 잘 방법이 떠오르지 않네용.. 개선방안 있으면 피드백 부탁드립니다 🙇‍♂️

2022-10-26 12:43 UTC, 2yujeong reviewed
안녕하세요 루키!
Keyword 엔티티가 계층 구조 때문에 구현하기 많이 힘들었을 것 같은데 정말 고생하셨습니다😭
말씀 드렸던 것처럼 조회 로직은 다 같이 코드보면서 고민해보는 게 좋을 것 같아요. 저도 지금은 더 좋은 방법이 생각나지 않네요😓 일단 흐름 파악만 했는데 요구 사항은 모두 잘 만족하고 있는 것 같아요👍🏼
코멘트는 CUD, 테스트 위주로 남겼어요. 개인적인 견해가 반영된 코멘트라서 읽어보시고 괜찮으면 반영해주세요!

2022-10-26 12:43 UTC, 2yujeong commented on backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordStepDefinitions.java
> +    public void 키워드를_부모_키워드와_함께_작성하고(int sessionId, String keywordName, int seq, int importance, long parentId) {
혹시 `@Given`을 의도하신 걸까요?

2022-10-26 12:43 UTC, 2yujeong commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +            .when().get()
url이 비어있네요..!

2022-10-26 12:43 UTC, 2yujeong commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +    );
개행이 조금 어색한 것 같은데 혹시 의도하신 걸까요?

2022-10-26 12:43 UTC, 2yujeong commented on backend/src/main/java/wooteco/prolog/roadmap/ui/KeywordController.java
> +        Long keywordId = keywordService.createKeyword(sessionId, createRequest);
```suggestion
    public ResponseEntity<Void> createKeyword(@PathVariable Long sessionId,
                                              @RequestBody KeywordCreateRequest createRequest) {
        Long keywordId = keywordService.createKeyword(sessionId, createRequest);
```

2022-10-26 13:40 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +        return findKeyword.orElse(null);
엇 그렇네요 개발할 때 뭔가 잘못 생각하고 있었던 것 같네요 ㅋㅋ.. 😅

2022-10-26 13:42 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +            request.getImportance(), sessionId, keywordParent
앗.. 정적 팩토리 메소드 + 빌더 패턴으로 구현하려고 했는데 중간에 한번 롤백하면서 없어진 것 같네요... 😅

2022-10-26 13:54 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +            request.getImportance(), sessionId, keywordParent
앗.. 그렇네요 뭔가 빌더를 쓰다가 정적 팩터리 메서드로 변경하면서 그대로 가져가버린 것 같네요 ㅋㅋ.. 빌더를 지우고 정적 팩터리 메서드만 사용해도 괜찮을 것 같아요..!!

2022-10-26 13:56 UTC, wishoon commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +            .when().get()
😅😅 꼼꼼하게 봐주셔서 감사합니다 이브~

2022-10-26 14:00 UTC, wishoon commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +    );
https://github.com/woowacourse/prolog/discussions/1041#discussioncomment-3730926 백엔드 테스트 개선에 대한 Discussion 내용을 바탕으로 작성했어요 😁

2022-10-26 14:04 UTC, wishoon commented on backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordStepDefinitions.java
> +    public void 키워드를_부모_키워드와_함께_작성하고(int sessionId, String keywordName, int seq, int importance, long parentId) {
헉.. 매의 눈이네요 👀 `@Given`을 의도한게 맞습니다 🙇‍♂️

2022-10-26 14:08 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +        keyword.validateKeywordParent();
이것도 개발할 때 뭔가 잘못 생각하고 있었던 것 같네요 ㅋㅋ.. 😅 지금 다시 생각해보니 create 할때는 이 검증이 필요가 없어도 괜찮을 것 같은데 혹시 어떻게 생각하시나요?.?

2022-10-26 14:09 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/Keyword.java
>      }
👍

2022-10-26 14:11 UTC, wishoon commented on backend/src/test/java/wooteco/prolog/roadmap/application/KeywordServiceTest.java
> +        Keyword child = createKeywordChildren(Keyword.createKeyword("List", "List에 대한 설명", 1, 1, 1L, parent));
앗 그렇네요.. 검증 추가하도록 할게요!!

2022-10-27 10:37 UTC, wishoon commented
https://github.com/woowacourse/prolog/commit/a7918b1c95b3aaec5a875b18ea3e8ac946ea8fad 의 내용에 대해서 https://github.com/woowacourse/prolog/pull/1098/commits/6531162dfb7f35504876ab2ec6c5eb530b4cddf9 으로 변경했습니다 

[변경 전]
![image](https://user-images.githubusercontent.com/48710213/198262871-1b1dd32c-7497-4249-9573-501e378f5d57.png)

[변경 후]
![image](https://user-images.githubusercontent.com/48710213/198262901-0c1a752d-51e4-4bce-9747-5a8371c8e21b.png)

2022-10-30 02:33 UTC, her0807 requested changes
위에 이브가 코멘트를 많이 달아두셔서 제가 첨언할 부분이 많지 않네요. 루키 고생하셨습니다

2022-10-30 02:33 UTC, her0807 commented on backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordStepDefinitions.java
> +     */
javadoc 로 히스토리 마킹해두어서 좋네요 👍🏻

2022-10-30 02:33 UTC, her0807 commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +//        Arrays.asList(
불필요한 주석은 제거해볼까요?

2022-10-30 02:33 UTC, her0807 commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +        Keyword keywordParent = findKeywordParentOrNull(request.getParentKeywordId());
전체 로직, 엔티티 연관관계만 살펴볼 때는 이해가 가는데, 
여기 로직만 보면 갑자기 키워드에 null 이 들어갈 수 있게 되는 점이 어색하네요.
javadoc 으로 표시해두면 후임자가 파악하기 수월할 것 같아요

2022-10-30 03:09 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
> +        Keyword keywordParent = findKeywordParentOrNull(request.getParentKeywordId());
좋은 의견이네요!! 반영하도록 할게요~!

2022-10-30 03:10 UTC, wishoon commented on backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
> +//        Arrays.asList(
Set으로 자료구조를 변경하기 전의 테스트 값이네요.. 제거해서 올리도록 할게요~

2022-11-17 03:50 UTC, her0807 approved these changes
루키 ~ 전체적인 코드 다시 확인했습니다 ☺️
머지해주시고, 공유해주시면 이어서 작업하겠습니다!

2022-11-17 03:50 UTC, her0807 commented on backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
> +    }
생성하는 시점에 validate vs validate 된 값을 생성자로 주입 두개 의 장단점과 루키가 선택한 방식에 이유를 듣고싶네요

2022-11-17 03:50 UTC, her0807 commented on backend/src/main/java/wooteco/prolog/roadmap/ui/KeywordController.java
> +    @GetMapping("/{sessionId}/keywords/{keywordId}/children")
/{sessionId}/keywords 까지가 기본 path 인 것 같은데

`@RequestMapping("/sessions/{sessionId}/keywords")` 로 기본 path 를 지정해주는건 어떨까요 ?

2022-11-17 05:39 UTC, wishoon commented on backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
> +    }
첫번째로는 검증의 시점이 빨라진다는 장점이 있을 것 같아요! 생성하는 시점에 내부에서 validate를 할 경우 그 만큼 검증의 시점이 느려져서 불필요한 객체가 생성되는 문제점이 있을 것 같네요!!

두번째로는 값 객체를 사용함으로서 얻는 이점이 있을 것 같네요!! 가격이라는 객체를 예시로 든다면 가격은 int 타입일 수도 있고, BigDecimal이 될 수도 있습니다. 이 처럼 가격의 타입이 변경되더라도 사용하는 클라이언트는 코드 변경에 대한 전파가 이루어지지 않는다는 장점이 있을 것 같네요!!

2022-11-17 05:59 UTC, wishoon commented
수달, 이브 리뷰 감사합니다~~ 머지할게용 😋

2022-11-17 07:08 UTC, merged