refactor: 메인 섹션 타이틀 반응형 css 개선
woowacourse/prolog pull request #1241
Opened 2023-04-21 08:55 UTC by D0Dam

해당 이슈 [바로가기](https://github.com/woowacourse/prolog/issues/1238)

- 메인 섹션의 타이틀의 정렬 방법이 창의 가로 넓이에 따라 변경되도록 수정
  - 760px 이하일때 column으로 정렬됨.

## 참고 예시
![prolog1](https://user-images.githubusercontent.com/51052049/233592342-604344de-8cf7-4e06-9e06-b494a41c613a.gif)

2023-04-28 07:40 UTC, feb-dain commented
mobile S에서는 인기있는 학습로그가 어떻게 보이나요?

2023-04-28 07:45 UTC, D0Dam commented
> mobile S 뷰에서는 인기 있는 학습로그가 어떻게 보이나요?

반영했습니다~! : [8ed2c30](https://github.com/woowacourse/prolog/pull/1241/commits/8ed2c309b7ae52d3ee0a3acda000b3f72db7c3da)
![222](https://user-images.githubusercontent.com/51052049/235086648-e7912b9c-1b17-4daa-b179-8100c48ca5fe.gif)

2023-04-28 08:04 UTC, sunhpark42 requested changes
코멘트확인 부탁드려용~!

2023-04-28 08:04 UTC, sunhpark42 commented on frontend/src/pages/MainPage/styles.ts
> +    font-size: 12px;
max-width가 360인 것으로 보아 모바일 환경 타겟인 것 같은데, font-size: 12px 은 너무 작다고 느껴질수 있을 것 같아요. 스크롤 동작을 추가한다던가 하는 방식으로 해결해볼 수 는 없을까요?

2023-05-02 07:44 UTC, D0Dam commented on frontend/src/pages/MainPage/styles.ts
> +    font-size: 12px;
@sunhpark42 

font-size가 12px이면 기본 환경보다는 좀 더 크게 표시해 주지만 주변 chip의 padding이 사라져서 아마 작게 느끼신 것 같습니다..!

우선, scroll 방식을 적용해 보았는데 이 때 scroll 시 나오는 scroll bar가 특정 환경에서 카테고리를 보는데 방해가 되는 것 같습니다.
이 때 서니의 의견을 들어보고 싶어요~!

1. 그냥 스크롤 바가 보이게 한다.
- 스크롤바가 그냥 보이도록 합니다.
- 맥과 윈도우 환경에서 보이는 스크롤바 위치, 디자인이 다릅니다.
  - prolog 프로젝트 내에서 기본적으로 사용하는 스크롤바 옵션이 정해져 있지 않습니다.

2. 스크롤바를 숨기는 css를 적용한다.
- 스크롤 바를 보이지 않게 합니다.
- 깔끔할 수 있지만 사용자가 카테고리 리스트가 스크롤 가능한지 파악하지 못할 수도 있습니다.
  - 하지만 이러한 경우는 서니의 말대로 모바일 타겟팅인데, 모바일의 경우 원래 터치 전까지 스크롤에 나오지 않습니다.

2번을 적용하게 되면 다음과 같은 `reset.styles.ts` 파일을 `src/styles` 폴더에 추가해 사용하려고 합니다.
```typescript
import { css } from '@emotion/react';

export const ResetScrollBar = css`
  ::-webkit-scrollbar {
    width: auto;
  }

  ::-webkit-scrollbar-track {
    -webkit-box-shadow: auto;
    -webkit-border-radius: auto;
    border-radius: auto;
    background: auto;
  }

  ::-webkit-scrollbar-thumb {
    -webkit-border-radius: auto;
    border-radius: auto;
    background: auto;
    -webkit-box-shadow: auto;
  }

  ::-webkit-scrollbar-thumb:window-inactive {
    background: auto;
  }
`;
```

이에 대해서 서니는 어떻게 생각하는지 의견을 들어보고 싶어요~!

2023-05-05 11:03 UTC, sunhpark42 commented on frontend/src/pages/MainPage/styles.ts
> +    font-size: 12px;
저는 의견을 드리면 가로스크롤인 경우에는 2번을 선호하는데요, 종종 스크롤바에 정보가 가리는 경우가 있고, 다른 방식으로 스크롤 동작이 가능하다는 것을 보여 줄 수 있기 때문이에요,   
말씀 주신 2번에서의 `깔끔할 수 있지만 사용자가 카테고리 리스트가 스크롤 가능한지 파악하지 못할 수도 있습니다.`이 단점은, ui 적으로 해결해 볼 수 있지 않을까 싶습니다~! 

예시로 어도비 페이지를 들고왔는데, 이 예시에서는 오른쪽 카드의 일부를 보이게 함으로써 우측에 컨텐츠가 추가로 있다는 느낌을 주게 되어 스크롤바 없이도 스크롤 가능한 영역이라는 느낌을 줄 수 있습니다. 이 방식 외에도 다른 방식을 적용해 볼 수 있을 것 같아서, 스크롤 UI 에대한 레퍼런스를 찾아보시면 더 좋을 것 같아요~!

![](https://user-images.githubusercontent.com/67677561/236441289-6c70a95d-205d-436c-84c6-108aa9c6ed34.png)

2023-05-10 07:19 UTC, D0Dam commented on frontend/src/pages/MainPage/styles.ts
> +    font-size: 12px;
자세한 정보 감사합니다!
현재 옆에 무언가가 있다는 정보를 추가적으로 주는 작업은 대부분의 스크롤에 적용되는 내용 같아서 저희 프론트 팀원들과 이야기 해서 해결 전략을 바탕으로 따로 이슈를 등록하겠습니다! 우선 스크롤 스타일을 없애는 방향으로 리팩토링 하였습니자.

2023-05-14 16:12 UTC, sunhpark42 commented on frontend/src/pages/MainPage/styles.ts
> +    font-size: 12px;
> 현재 옆에 무언가가 있다는 정보를 추가적으로 주는 작업은 대부분의 스크롤에 적용되는 내용 같아서 저희 프론트 팀원들과 이야기 해서 해결 전략을 바탕으로 따로 이슈를 등록하겠습니다! 

🙆‍♀️🙆‍♀️

2023-05-14 16:13 UTC, sunhpark42 approved these changes
수정된 부분 확인 했습니다. 감사합니다:) 👍

2023-05-15 03:21 UTC, merged