test: StudylogDocumentService 테스트 코드 작성
woowacourse/prolog pull request #1301
Opened 2023-05-17 08:56 UTC by donghae-kim

## #️⃣연관된 이슈

> 연관된 이슈 번호를 모두 작성해주세요
> #1280 
> ex) #이슈번호, #이슈번호

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
AbstractStudylogDocumentService, StudylogDocumentService, FakeStudylogDocumentService 코드에 관한 테스트 코드 작성

2023-05-17 16:03 UTC, Hyeon9mak requested changes
안녕하세요 오션 라온, 바쁜 일정 중에 테스트 코드 작성에 고생하셨어요.
mock 을 이용한 테스트는 편리하고 좋지만, 정말 유의미한 '검증'을 진행한 것인지 고민이 필요할 거 같아요.
남긴 코멘트 확인해주세요 🙇‍♂️

2023-05-17 16:03 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
동등비교 원소들을 `contains`, `containsExactly`, `containsExactlyInAnyOrder` 로 확인해봐도 좋겠네요!

2023-05-19 07:42 UTC, donghae-kim commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
꼼꼼하지 못했던 것 같습니다 .. 
조금 더 의미있는 테스트를 위해 `studylogDocumentRepository.findById(1L)`일 때 반환값을 Optional.empty로 만들면서 이 경우 어떤 예외가 발생하는지에 대한 테스트로 변경하였습니다.

2023-05-19 07:55 UTC, donghae-kim commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
동등성 비교를 위해서 isEqualTo 대신 containsExactly를 사용하였습니다 !
다만 현재 List<String> 타입에서 isEqualTo를 사용해도 동등비교가 가능한데,  `contains, containsExactly, containsExactlyInAnyOrder`를 동등비교시 관습적으로 사용하는 것일까요 ?

2023-05-21 08:38 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +class FakeStudylogDocumentServiceTest {
음... 제가 의도를 잘 이해하지 못한거 같아요. 
fake 클래스를 테스트 한 이유는 본래 프로덕션 코드가 테스트 하기 어렵고 난해해서 fake 클래스를 테스트한 것 아닌가요?
"fake 클래스(테스트 더블)이 우리의 의도대로 동작하는지 확인할 수 있다." 가 의미가 있는지 잘 모르겠어요 😢

2023-05-21 08:40 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
테스트 명칭 때문에 남긴 코멘트였어요. 🙏 
그렇다면 이 테스트는 "StudylogDocument 저장 테스트" 가 아니라 "studylogDocumentRepository#save 호출 테스트" 가 되겠네요.

2023-05-21 08:41 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
관습으로까진 생각해보지 않았는데, assertj 에서 제공하는 편의 메서드를 활용하면 가독성이 좋아지다보니 마다할 필요가 없을 것 같아요.

2023-05-21 08:42 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +class FakeStudylogDocumentServiceTest {
오션 라온이 검증해야 할 건 결국 프로덕션 코드가 제대로 동작하는지 여부 아닐까요?

2023-05-21 08:44 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
찾지 못하면 `studylogDocumentService` 에서 예외처리를 한다는 테스트가 되겠군요.

2023-05-21 08:44 UTC, Hyeon9mak commented
오션 라온 고생하셨어요. 남겨드린 코멘트에 대해 답변 주시면 확인 후 approve 하겠습니다 🙇‍♂️

2023-05-26 09:24 UTC, donghae-kim commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +class FakeStudylogDocumentServiceTest {
현구막의 의견을 들어보니 Fake 객체 자체를 테스트할 필요는 없는 것 같습니다. `StudylogDocumentService`를 사용하는 테스트에서 이를 대체하기 위한 용도로써 `FakeStudylogDocumentService`를 사용해야 될 것 같습니다. 
그럼 `StudylogDocumentService`는 엘라스틱서치에 의존적인데 이를 테스트 하기 위해서는 로컬에서 엘라스틱서치를 띄워서 테스트하거나, `ElasticsearchRestTemplate` fake객체를 만들어서 테스트 해야할까요 ?

2023-05-26 09:24 UTC, mcodnjs commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
그렇네요, 잘 저장되는 것을 확인하는 것이 아니라 호출 테스트라는 명칭이 더 자연스러울 것 같아요! 수정하였습니다 ~

2023-05-26 09:24 UTC, mcodnjs commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +    }
아하 그렇군요 감사합니다 👍

2023-05-31 07:45 UTC, merged

2023-06-02 08:21 UTC, Hyeon9mak commented on backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java
> +class FakeStudylogDocumentServiceTest {
> 현구막의 의견을 들어보니 Fake 객체 자체를 테스트할 필요는 없는 것 같습니다. StudylogDocumentService를 사용하는 테스트에서 이를 대체하기 위한 용도로써 FakeStudylogDocumentService를 사용해야 될 것 같습니다.

👍 👍 

> 그럼 StudylogDocumentService는 엘라스틱서치에 의존적인데 이를 테스트 하기 위해서는 로컬에서 엘라스틱서치를 띄워서 테스트하거나, ElasticsearchRestTemplate fake객체를 만들어서 테스트 해야할까요 ?

넵, 이미 정답을 알고 계시는군요 😄 👍