feat : 커리큘럼 ID로 키워드들 조회 API 구현
woowacourse/prolog pull request #1472
Opened 2023-08-02 07:51 UTC by java-saeng

> 연관된 이슈 번호를 모두 작성해주세요

- #1461 

## 📝작업 내용

커리큘럼 ID로 키워드들 조회
- 세션 ID 사용 X

2023-08-02 08:53 UTC, nuyh99 approved these changes
고생하셨습니다!!!
자유롭게 반영해주시면 좋을 것 같아서 Approve 하겠습니당

2023-08-02 08:53 UTC, nuyh99 commented on backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
> +            .filter(it -> it.getParent() == null)
Keyword에게 최상위 키워드인지 물어보는 메서드를 만들고 참조해도 좋을 것 같아요!

근데 한 편으로 궁금한 점이 파라미터로 받은 키워드 리스트가 최상위 키워드인지 확인하고 파싱하는 작업이 괜찮을 지 의문입니다. 외부에서 최상위 키워드만 들어오는 것보다 지금이 나은 지 궁금해요

2023-08-02 08:53 UTC, nuyh99 commented on backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
> +    public KeywordsResponse findAllKeywords(final Long curriculumId) {
KeywordService에 넣지 않은 이유가 있을지 궁금합니다!

2023-08-02 08:53 UTC, nuyh99 commented on backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
> +    public KeywordsResponse findKeywords(@RequestParam final Long curriculumId) {
로드맵 대격변 패치를 위하신 거였나보군요!
```java
public RoadmapResponse findByCurriculumId(@RequestParam final Long curriculumId)
```

Roadmap이라는 새로운 비즈니스 용어를 코드에서 사용하신다면 위와 같은 시그니처가 유지보수면에서 더 좋을 것 같다고 생각합니다

2023-08-02 08:53 UTC, nuyh99 commented on backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
> +    void findAllKeywords() throws Exception {
커리큘럼이 없는 분기도 테스트하면 좋겠어요!

2023-08-02 08:55 UTC, amaran-th requested changes
수고하셨습니다!
수정되었으면 하는 부분이 조금 있어서 코멘트 달았습니다.
확인 부탁드려요!

2023-08-02 08:55 UTC, amaran-th commented on backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
> +            .filter(it -> it.getParent() == null)
이 부분을 isTopKeyword()와 같은 메서드로 분리하면 코드 가독성이 더 좋아질 것 같아요!

2023-08-02 08:55 UTC, amaran-th commented on backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
> +                "해당 커리큘럼이 존재하지 않습니다. curriculumId = " + curriculumId));
프로젝트에서 커스텀 예외를 사용하고 있으니 가급적이면 커스텀 예외를 활용해주시는 게 유지보수 측면에서 좋을 것 같습니다!

2023-08-03 07:57 UTC, java-saeng commented on backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
> +    void findAllKeywords() throws Exception {
커리큘럼은 controller에서 RequestParam으로 받고 있습니다.
이때 커리큘럼 ID가 존재하지 않으면 아예 서비스 쪽으로 들어오지 않을텐데 예외 테스트가 필요할까요??

2023-08-03 07:57 UTC, java-saeng commented on backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
> +            .filter(it -> it.getParent() == null)
반영했습니다!

2023-08-03 08:01 UTC, java-saeng commented on backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
> +    public KeywordsResponse findKeywords(@RequestParam final Long curriculumId) {
`findRoadMapKeyword` 로 수정했습니다!

2023-08-03 08:04 UTC, java-saeng commented on backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
> +            .filter(it -> it.getParent() == null)
개인적으로 
최상위 키워드
ㄴ 자식 키워드

이렇게 보여주기 위함은 UI 적인 요소라 DTO에서도 해도 되지 않을까라는 생각이 들어요.

2023-08-03 08:07 UTC, amaran-th commented
RoadmapServiceTest를 실행하면 NPE가 뜨는데 혹시 이유를 아시나요?
![image](https://github.com/woowacourse/prolog/assets/81465068/2bcbd5d7-b69e-469e-9ad8-31e65ea6ee53)

2023-08-03 09:28 UTC, nuyh99 commented on backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
> +    void findAllKeywords() throws Exception {
1. API 요청 시 아무 Id를 적었을 때
2. 해당 서비스를 다른 컨트롤러에서 사용하면 1번의 문제가 동일하게 발생
3. 해당 서비스를 다른 서비스에서 의존할 때

위와 같은 상황에서 문제가 될 것 같아요!

```java
        final Curriculum curriculum = curriculumRepository.findById(curriculumId);
```
만약 위의 문제들이 절대 발생할 일 없는 상황이라면 위와 같은 형태로 메서드 내에서 사용해야 하지 않을까요?!

2023-08-03 12:11 UTC, java-saeng commented
> RoadmapServiceTest를 실행하면 NPE가 뜨는데 혹시 이유를 아시나요? ![image](https://user-images.githubusercontent.com/81465068/258044884-2bcbd5d7-b69e-469e-9ad8-31e65ea6ee53.png)

![image](https://github.com/woowacourse/prolog/assets/62413589/8a2ae528-e9d8-4367-96c0-4d6072d0f817)

혹시 다시 한번 해주실 수 있나요?
@amaran-th

2023-08-07 06:24 UTC, merged