Refactor: UNVALIDATED 에서 GUEST 로 권한을 변경하고 가입시 기존 권한을 CREW 에서 GUEST 로 변경한다.
woowacourse/prolog pull request #1564
Opened 2023-09-28 17:21 UTC by splitCoding

## #️⃣연관된 이슈

- close #1563

## 📝작업 내용

- 기존에 존재하던 Role 의 `UNVALIDATED` 를 `GUEST` 로 변경한다.
- GIthubLogin 시 부여되는 권한을 `CREW` 에서 `GUEST` 로 변경한다.
  - `Role` 에 권한에 중요도 (`importance`) 를 부여한다.
- 회원의 권한을 변경하는 기능을 구현한다. 
  - API
    - `AccessToken` , `PATCH /member/{member_id}/role`
  - 변경을 요청하는 멤버의 권한을 검증한다. ( 권한 변경을 가능한 멤버를 `manager` 라고 칭하겠습니다. )
  - 환경별 테스트 격리를 위해서 `manager.role` 을 `application.yml` 속성에 추가한다.
    - 기본  : `Role.COACH`
    - test 환경 : `Role.CREW `
-  CREW 권한이 필요한 아티클 기능에 검증로직을 추가한다.

- 추가적으로 바뀐 로직으로 통해 test 모두 수정

2023-09-30 04:35 UTC, wonyongChoi05 requested changes
스플릿 추석에 정말 수고 많으셨습니다! 큰 변경 사항은 아니고, 간단하게 남겨놓았으니 확인 부탁드려용

2023-09-30 04:35 UTC, wonyongChoi05 commented on backend/src/acceptanceTest/java/wooteco/prolog/steps/LoginStepDefinitions.java
> +    public void 멤버가크루역할로로그인을하고(String member) {
원래 띄워쓰기에 _(언더스코어) 사용하지 않나용?

2023-09-30 04:35 UTC, wonyongChoi05 commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +            .orElseThrow(() -> new BadRequestException(ARTICLE_NOT_FOUND_EXCEPTION));
저는 보통 Repository에서 Optional로 뽑았을 때 null에 대한 처리를 Repository로 이관하는 편인데, 스플릿은 어떻게 생각하시나요?(이미 프롤로그에서는 서비스에서 담당하고 있긴 하지만 궁금해서 여쭤봅니다 ㅋㅋㅋ)

```java
default PrimaryIngredient getById(Long id) {
     return findById(id)
             .orElseThrow(() -> new BadRequestException(ARTICLE_NOT_FOUND_EXCEPTION));
}
```

2023-09-30 04:35 UTC, wonyongChoi05 commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +        }
어떤 검증에서는 도메인이 예외까지 던지고, 어떤 검증에서는 도메인한테 메시지만 전달받아서 서비스 계층에서 예외를 던지는데 이 둘이 다른 상황은 뭐가있을까여?? 아니면 단순 실수일까요??

2023-09-30 04:35 UTC, wonyongChoi05 commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    }
Member보단 Role의 책임 아닐까요?

2023-09-30 05:20 UTC, splitCoding commented on backend/src/acceptanceTest/java/wooteco/prolog/steps/LoginStepDefinitions.java
> +    public void 멤버가크루역할로로그인을하고(String member) {
새로 작성된 인수테스트를 제외한 기존 인수테스트의 조건에 맵핑될 메서드명을 다 해당 방식으로 작성했더라구요 컨벤션이였던 것으로 파악되서 통일되게 작성했습니다!! ( 저도 언더 스코어가 좋아요ㅎㅎ )

2023-09-30 05:23 UTC, splitCoding commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +            .orElseThrow(() -> new BadRequestException(ARTICLE_NOT_FOUND_EXCEPTION));
저는 비즈니스 상황때문에 생기는 검증 처리는 Service 레어이가 하는 것이 맞다고 생각하는 편입니다!!😊

사실상 Repository 가 id 를 통해 무엇인가를 찾을때 해당 값이 무조건 있어야 한다는 비즈니스 로직상의 상황을 알고 있을 필요는 없다고 생각해요ㅎㅎ!! 😁

2023-09-30 05:27 UTC, splitCoding commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +        }
제가 코드를 파악할때는 모든 예외는 서비스에서 던지는 것으로 보이는데 혹시 현재 코드에서 언제 도메인 예외를 던지는 상황인지 설명 한번 부탁드립니다!!

2023-09-30 05:44 UTC, splitCoding commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    }
Role 에게 해당 부분의 책임을 주는 것에서는 ( Role 에게 전달하는 Role 과 같은 지 물어본다 )

```java
    public boolean isGuest() {
        return this.role.equals(GUEST);
    }

    public boolean isCrew() {
        return this.role.equals(CREW);
    }
```
equals 메서드도 Role 객체에서 제공하는 메서드니 이런 방식으로 바꿀 수 있을 것 같아요!!

근데 추가로 Role 에 importance 를 부여한 상황에서 

```java
  public boolean hasLowerImportanceRoleThan(final Role role) {
      return this.role.hasLowerImportanceThan(role);
  }
```
위에 메서드를 이용하면 유지보수하기 좋을 것 같아서 해당 메서드로 변경했습니다!!

2023-10-01 01:08 UTC, wonyongChoi05 commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +        }
<img width="891" alt="스크린샷 2023-10-01 10 04 46" src="https://github.com/woowacourse/prolog/assets/94087228/0f7f931d-f73a-4a44-94a8-c5d8dd89d75d">



이건 아티클 엔티티인데요! 여기서는 분명 객체가 예외를 던지는 것 까지 담당하고 있어요. 그래서 예외 처리를 어떤 방식으로 하는게 맞는건지 헷갈려서 물어봤습니다 😭

2023-10-01 01:08 UTC, wonyongChoi05 commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    }
좋은 접근이네요! 👍🏻

2023-10-01 01:10 UTC, wonyongChoi05 approved these changes
스플릿 수고하셨어요! 앞으로도 프롤로그 아티클 서비스 잘 부탁드립니다 ㅎㅎ 🙇‍♂️🙇‍♂️

2023-10-04 08:19 UTC, splitCoding commented on backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
> +        }
베베의 의견 완전히 파악됐습니다!! Member 에게 Owner 인지만 메시지로 전달받아서 Service 에서 예외를 던지는 방식을 말하시는 거군요!!😊

이 부분에 확실히 일관성이 없었네요😭
베베의 의견대로 일관성을 맞추는게 더 좋아보입니다!! 기존에 스쿼드에서 작성하고 사용하고 있던 코드라 스쿼드 팀원들과 함께 말해보도록 할께요!!👍

2023-10-04 13:10 UTC, merged