feat(학습로그 작성, 전체보기) : 고정된 값을 반환하는 API 작성
woowacourse/prolog pull request #35
Opened 2021-05-16 12:30 UTC by sihyung92

1. 학습로그 전체보기, 개별 글보기, 카테고리 전체보기, 글 작성 API 생성
2. controller 단위테스트 작성

2021-05-17 20:24 UTC, gracefulBrown requested changes
구현하시느라 고생 많으셨습니다!
Dao 부분을 어떻게 처리할 지 회의가 필요할 것 같네요 :)

Dao 부분은 구현하지 않더라도 Service 부분은 구현할 수 있을 것 같은데 
Service 부분을 구현하시면 domain -> dto 라던지 좀 더 많은 코드가 필요해 보이네요ㅎㅎ
이 부분을 구현하신 후 한번 더 리뷰하겠습니다!

그 전에 몇가지 컨벤션과 관련된 코멘트 위주로 남겨보았습니다!

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/service/StudyLogService.java
> +        return null;
아직 dao의 기능이 구현되어있지는 않았지만 service로직은 구현이 가능한 거 같은데 이 부분을 구현해보면 어떨까요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/dao/StudyLogDao.java
> +public class StudyLogDao {
JdbcTemplate을 쓸 지 hibernate를 쓸 지 고민해봐야겠네요 :)

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/LogResponse.java
> +public class LogResponse {
StudyLog의 Response가 맞나요?
그렇다면 StudyLogResponse로 사용하는건 어떤가요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/StudyLog.java
>  public class StudyLog {
생성시간 정보가 필요할 것 같아요 :)

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/dao/StudyLogDao.java
> +    }
CategoryDao로 분리해보면 어떨까요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/domain/Category.java
> +public class Category {
생성 시간 정보가 필요하겠네요~

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/AuthorResponse.java
> +    private Long authorId;
```suggestion
    private Long id;
```

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/CategoryResponse.java
> +    private String categoryName;
```suggestion
    private Long id;
    private String name;
```

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/service/StudyLogService.java
> +    public CategoryResponses findAllCategories() {
CategoryResponses를 별도로 만들어 줄 필요가 있을까요?
List< CategoryResponse>로 사용할 때와 어떤 차이가 있을까요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/LogResponse.java
> +    private LocalDateTime issuedDate;
엔티티 별로 모두 생성시간 정보가 필요한데 이 때 사용하는 변수명(컬럼명)을 통일하면 어떨까요?
생성시간과 함께 수정시간도 필요할 것 같습니다.

ex) 
- createdAt
- updatedAt

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/LogResponse.java
> +
두 줄이 띄워졌네요ㅎㅎ

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/LogRequest.java
> +    String content;
접근 제한자를 붙여주면 어떨까요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/StudyLogController.java
> +@RequestMapping("/logs")
현재는 StudyLog와 Log라는 용어가 혼용되어 사용중인데요~
StudyLog vs Log 중 결정해서 다른 코드에도 똑같이 통일해도 좋을 것 같아요!

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/StudyLogController.java
> +        return ResponseEntity.ok(studyLogResponses);
mock 데이터를 응답해주는 로직 👍

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/StudyLogController.java
> +        List<LogResponse> rowLogResponses = Collections.singletonList(
rowLogResponses에서 row가 의미하는 것은 무엇인가요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/web/controller/StudyLogController.java
> +    public ResponseEntity<LogResponse> showLog(@PathVariable Long logId){
전체 path가 `/logs/{logId}`가 될 것 같은데
logs 이후에 오는 값은 log의 id임을 유추할 수 있으므로 id만 표기하는건 어떤가요?

```suggestion
    @GetMapping("/{id}")
    public ResponseEntity<LogResponse> showLog(@PathVariable Long id){
```

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/main/java/wooteco/studylog/log/StudyLog.java
> +    private List<String> tags;
tag는 객체 도출을 하지 않았네요?ㅎㅎ

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/test/java/wooteco/studylog/log/acceptance/StudyLogAcceptanceTest.java
> +        given(studyLogService.findAll()).willReturn(studyLogResponses);
현재는 이 구문이 없어도 잘 동작해야하지 않나요?

2021-05-17 20:24 UTC, gracefulBrown commented on backend/src/test/java/wooteco/studylog/log/acceptance/StudyLogAcceptanceTest.java
>  public class StudyLogAcceptanceTest {
테스트 👍

2021-05-18 06:26 UTC, sihyung92 commented on backend/src/main/java/wooteco/studylog/log/service/StudyLogService.java
> +        return null;
넹!! 우선적으로 프론트단에서 요청이 가능한 API를 만들어주기 위해 빨리 PR했는데 다음 페어 때 이 부분도 구현하도록 하겠습니다

2021-05-18 06:27 UTC, sihyung92 commented on backend/src/main/java/wooteco/studylog/log/dao/StudyLogDao.java
> +public class StudyLogDao {
넵~! 그렇다면 내일 페어 때 DB단까지 완성하겠습니다!

2021-05-18 06:28 UTC, sihyung92 commented on backend/src/main/java/wooteco/studylog/log/web/controller/dto/LogResponse.java
> +public class LogResponse {
로깅의 로그와 헷갈릴 여지가 있는 것 같습니다 :) 페어와 토의해 보겠습니다

2021-05-20 05:59 UTC, closed without merging