feat: 리포트 생성 페이지 기능을 구현(제목, 설명, 학습로그 등록)
woowacourse/prolog pull request #435
Opened 2021-09-29 12:42 UTC by devhyun637

리포트 생성 페이지에서 역량 부분과 학습로그 역량추가 부분 제외하고 구현하였습니다. 
아직 기능이 완성된 것이 아니기 때문에 리포트 등록을 누르면 알림 처리를 해놓았고, 
역량 부분과 학습로그에 선택된 역량 추가가 되면 API 연동하겠습니다!

- [x] 사용자는 리포트가 없을 시, 리포트 등록 버튼을 통해서 리포트를 생성할 수 있다.
- [x] 자신의 리포트가 아니라면 생성할 수 없다.
- [x] 로그인한 사용자는 접근할 수 없다.

### 기본 사항
- [x] 제목을 입력 안하면 날짜 + 닉네임으로 자동 생성된다.
- [x] 설명은 필수사항이 아니다.

### 학습로그 가져오기 모달
- [x] 학습로그 불러오기 버튼을 통해 학습로그를 추가할 수 있는 모달창을 띄울 수 있다.
- [x] 모달에서는 각 레벨별 학습로그를 선택할 수 있다.
- [x] 학습로그는 페이지네이션이 가능하다. (숫자 페이지네이션 대신 더보기 버튼)
- [x] 해당 모달을 열었을 때의 선택된 개수를 확인할 수 있다.
- [x] 이미 선택한 학습로그는 선택이 불가능하다.

### 학습로그 목록 표
- [x] 선택한 학습로그는 학습로그 목록에서 확인이 가능하다.
- [x] 학습로그 목록에서 선택한 학습로그를 선택취소(삭제)할 수 있다.
- [x] 학습로그 목록은 페이지네이션이 가능하다.
- [x] 가장 최근에 추가된 학습로그가 첫 페이지의 가장 상위에 쌓인다.

### 미완성 부분
- 학습로그에 선택된 역량을 추가한다.
- 리포트 메뉴의 아이콘을 변경한다.

부족한 부분 있으면 더 말씀해주세요~~!!!
커밋이 너무 많이 쌓여서 한번 머지하고 스프린트 내로 리포트 목록 및 수정페이지 만들겠습니다! (역량 부분 제외)

<img width="1184" alt="스크린샷 2021-09-29 오후 9 41 03" src="https://user-images.githubusercontent.com/59258239/135270178-1bbcacb6-292e-47fe-a1a9-f261ac9227ed.png">
<img width="1312" alt="스크린샷 2021-09-29 오후 9 40 27" src="https://user-images.githubusercontent.com/59258239/135270080-34299231-117f-4cc8-962b-33b2453d3e06.png">
<img width="1343" alt="스크린샷 2021-09-29 오후 9 41 37" src="https://user-images.githubusercontent.com/59258239/135270253-687b1725-a704-4813-906c-70b52fb61471.png">

2021-09-29 13:42 UTC, gracefulBrown requested changes
눈에보이는 백엔드 코드만 몇가지 리뷰했습니다!

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/test/java/wooteco/prolog/studylog/application/ReportServiceTest.java
> +        ReportRequest reportRequest = createRequest("jsons/report_post_request.json");
제이슨파일으로 분리해둔 이유가 있나요?
해당 도메인의 변경이 생겼을 때 제이슨 파일로 관리하면 타입 체크가 불가능하지 않을까요?

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/Report.java
> +public class Report {
studylog 패키지가 아닌 독립된 report 패키지로 관리하면 어떨까요?

prolog
ㄴstudylog
ㄴreport 

이렇게요

report 패키지 내에 studylog처럼 레이어별로 나누어 관리하면 좋을 것 같습니다 :)

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/ui/AbilityController.java
> +    @GetMapping("parent-only")
계층을 통해 리소스를 표현하기 보다는 필터링을 통해 표현하면 어떨까요?
ex) 
/abilities?type=parents
/abilities?depth=1

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/ui/ReportController.java
> +    @GetMapping("/{username}/}reports")
중괄호 닫는 부분이 하나 빠져야 하는건가요?
```suggestion
    @GetMapping("/{username}/reports")
```

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/ui/ReportController.java
> +    @GetMapping("/{username}/}reports")
아래의 두 표현은 비슷하지만 다른 의미를 지니고 있습니다.
- /{username}/reports: 특정 사용자의 리포트를 가리킴
- /reports?member={username}: 리포트 중 작성자가 특정 사용자인 리포트를 가리킴

저는 두번째 표현을 써보는게 어떨지 추천하고싶은데요
이유는 크게 다르진 않지만 나중에 필터링을 하거나 리포트 목록을 조회하는 경우 조건이 추가적으로 생길 때 좀 더 유연하게 확장할 수 있을 것 같습니다.

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/repository/ReportRepository.java
> +    @Query("select r from Report r where r.member.username = :username")
쿼리를 명시적으로 지정해주는게 불필요한 조회를 막을 수 있어서 지정해준건가요? (의도가 궁금해서 물어보는거에요ㅎㅎ)

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/abilitygraph/GraphAbility.java
> +public class GraphAbility implements Updatable<GraphAbility> {
프론트엔드의 표현과 커플링이 있는 클래스 이름으로 보입니다.
향후 그래프로 표현되지 않을 수 있고 여러 방법으로 표현될 수 있는데 도메인 이름에 그래프라고 명시되어있어서 조금 의미가 모호해지는거 같아요. 차라리 ReportedAbility가 조금더 어울리지 않을까요? 리포트에 적용된 역량이라는 의미로...ㅎㅎ

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/ReportedAbility.java
> +public class ReportedAbility {
사용하지 않는 클래스!

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/studylog/ReportedStudylog.java
> +    private Studylog studylog;
만약에 report가  studylog와 별도의 패키지(컨텍스트)로 분리된다면 studylog를 참조하는것 보다는 간접참조를 하는건 어떨까요?
> 객체를 참조하기 보다는 아이디만 참조하기

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/ablity/AbilityRelationship.java
> +    private Ability target;
source가 parent고 target이 child인가요?
명칭이 조금 모호한 것 같은데 parent / child는 어떤가요?

2021-09-29 13:42 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    private List<Ability> abilities;
Ability -> Member 의 단방향 참조만 존재하면 안되나요?
양방향 참조가 필요한 이유가 있나요?

2021-09-30 13:16 UTC, bperhaps commented on backend/src/test/java/wooteco/prolog/studylog/application/ReportServiceTest.java
> +        ReportRequest reportRequest = createRequest("jsons/report_post_request.json");
Request, Response DTO를 생성하는게 너무나도 고역이라서... ObjectMapper의 힘을 빌리고 싶었습니다...ㅜㅜㅜ 쥬르륵....

2021-09-30 13:17 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/Report.java
> +public class Report {
좋습니다 👍  저도 사실 하면서 이게 studylog 의 바운디드 컨텍스트가 아닌것같다는 생각을 계속 했습니다...ㅎㅎ

2021-09-30 13:32 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/ui/AbilityController.java
> +    @GetMapping("parent-only")
@Hyeon9mak @sunhpark42 확인 부탁 드립니다.

2021-09-30 13:34 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/ui/ReportController.java
> +    @GetMapping("/{username}/}reports")
좋은것 같습니다! queryParam을 사용하는게 더욱 유연하게 느껴지네요!!!

저 오탈자는... 있는데 어떻게 정상 작동이 됐던거지..? 스프링... 갓...

2021-09-30 13:37 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/ui/ReportController.java
> +    @GetMapping("/{username}/}reports")
일단 두가지 API를 모두 유지시키고 이전 버전은 Deprecated 시켜놨습니다.

2021-09-30 13:38 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/repository/ReportRepository.java
> +    @Query("select r from Report r where r.member.username = :username")
메서드 네이밍으로 하는거는 메서드 이름이 마음에 안들어서... 직접 지정 했습니다..ㅎㅎ member가 아니라 username으로 검색을 하고싶어서요.. member로 검색하면 불필요하게 member를 select해와야하는 경우가 너무 많더라구요!

2021-09-30 13:39 UTC, gracefulBrown commented on backend/src/test/java/wooteco/prolog/studylog/application/ReportServiceTest.java
> +        ReportRequest reportRequest = createRequest("jsons/report_post_request.json");
쥬륵... 이번엔 이렇게 진행하고 다른 방법을 찾아보시죠ㅠㅠ

2021-09-30 13:40 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/abilitygraph/GraphAbility.java
> +public class GraphAbility implements Updatable<GraphAbility> {
이부분은 약간 논의가 필요해 보입니다!!
지금 연관관계를 보면
Report - Graph - GraphAbility - Ability 
이 형식으로 되어있어서 GraphAbility를 ReportedAbility로 하면 이 Ability가 속하는 부분이 어디인지 약간 애매해 질 것 같아요!

아... 저는 Graph를 Report내의 또 다른 컴포넌트(도메인)으로 취급해서 이런 설계가 나온 것 같습니다!

2021-09-30 13:53 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/ReportedAbility.java
> +public class ReportedAbility {
오잉..... 뭐지.....

2021-09-30 13:54 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/studylog/ReportedStudylog.java
> +    private Studylog studylog;
오.....!!! 너무 좋습니다..!!
너무 적용해 보고 싶었던건데 드디어 해보는 기법이네요ㅜㅜㅜㅜ

2021-09-30 14:12 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/studylog/ui/AbilityController.java
> +    @GetMapping("parent-only")
아! 임시로 사용한 URI라 서니가 편하신대로 알려주시면 언제든지 변경 가능함니당

2021-09-30 14:17 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/studylog/domain/ablity/AbilityRelationship.java
> +    private Ability target;
실제로는 source가 child고, target이 parent인 상태로 동작하고 있습니다!!
처음엔 'child, parent 명명을 사용하는게 직관적이지 않을까?' 했는데, "depth가 더 깊은 부모자식 관계도 표현할 때도 자연스럽게(확장이 가능하게) source, target 을 사용하는게 좋을거 같다."는 너잘 의견에 저도 동의해서 source, target이 되었어요.

그런데 Ability 부분 코드를 처음 보신 브라운이 모호하다고 느끼셨다니 또 고민이 되네요... 😵

2021-09-30 14:19 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    private List<Ability> abilities;
MemberController를 통해서 들어오는 `/members/{memberId}/abilities` API에서 member의 abilities를 조회하는 로직이 있어요! 
member에서 ability를 조회하는 방향 때문에 필요하다고 생각해서 양방향 참조를 만들었습니다! 
혹시 이런 경우에도 Ability에서 Member를 찾도록 해야하나요?!

2021-09-30 14:24 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    private List<Ability> abilities;
@Hyeon9mak 쿼리로 해결하라고 했었잖아유우우우 뿌우우우엥

2021-09-30 14:25 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    private List<Ability> abilities;
아 헐 새까맣게 잊었다

2021-09-30 14:40 UTC, bperhaps commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/studylog/ReportedStudylog.java
> +    private Studylog studylog;
적용 완료했습니다. 현재는 그냥 Repository를 불러와서 id기반으로 Entity를 가지고 오고 있는데요, 추후 MSA로 분리하거나 할때 Infrastructre 레이어를 만들어서 REST CALL을 통해 Studylog 데이터를 가져오는 식으로 리팩토링 하면 될 것 같습니다.

2021-09-30 14:43 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/member/domain/Member.java
> +    private List<Ability> abilities;
Member가 Ability를 아주 꿈에도 모르게 바꿨슴다!

2021-10-01 08:18 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/ablity/AbilityRelationship.java
> +    private Ability target;
일단 요롷게 가시죠ㅋㅋ

2021-10-01 08:19 UTC, gracefulBrown commented on backend/src/main/java/wooteco/prolog/studylog/domain/report/abilitygraph/GraphAbility.java
> +public class GraphAbility implements Updatable<GraphAbility> {
Graph라는 개념이 조금 생소하긴 하지만 일단 요롷게 가보시죠!

2021-10-01 08:20 UTC, merged