feat: Card hover 시 가시성 향상을 위해 UI 개선
woowacourse/prolog pull request #865
Opened 2022-05-02 08:06 UTC by kwannee

### 개선 사항
- [x]  Card 링크 영역 변경한다.
    - 프로필, 제목, 태그와 내용에 준다.(제외: 날짜,)
    - 나머지는 pointer 주지 않는다.
- [x]  hover 시 tranform 올린다.
    - 애니메이션 추가
- [x]  텍스트 언더라인 삭제한다
- [x]  텍스트 bold 스타일 삭제한다

#838

2022-05-02 08:28 UTC, sunhpark42 requested changes
코드 구조 파악하기 어려우셨을텐데, 깔끔하게 작업이 잘 된 것 같습니다👍 고생하셨습니다~ 리뷰 한 번 확인 부탁드려요.

2022-05-02 08:28 UTC, sunhpark42 commented on frontend/src/components/Items/PopularStudylogItem.tsx
> +        <span css={[DateAreaStyle]}>{new Date(createdAt).toLocaleDateString('ko-KR')}</span>
날짜는 포함하지 않은 이유가 있을까요? 기존 날짜까지 링크영역에 포함시켜뒀던건, 링크 영역을 카드영역과 프로필 영역으로 구분하기 위함이었는데, 날짜가 링크영역에서 제외된 이유가 궁금합니다~

2022-05-02 11:26 UTC, kwannee commented on frontend/src/components/Items/PopularStudylogItem.tsx
> +        <span css={[DateAreaStyle]}>{new Date(createdAt).toLocaleDateString('ko-KR')}</span>
날짜를 제외한 것은 사용자로 하여금 날짜 클릭 시에도 어떤 기능이 있다고 오인하는 것을 방지하기 위함이었습니다!

카드 hover UI를 바꾸다 보니, 글의 `타이틀`과 `프로필` 간의 hover css 차이가 없어졌고, 이를 분명히 구분 시킬 필요를 느꼈습니다.  기존 상단 영역의 div를 통째로 감싸던 Link를  미션과 타이틀만 감싸도록 했고, 그 결과 cursor가 pointer가 되는 영역을 기준으로 `타이틀`과 `프로필` 두 부분으로 구분되도록 할 수 있었습니다.

만약 여기에 날짜도 포함하게 되면 hover 시 cursor가 pointer가 되는 영역이 타이틀(미션 포함), 프로필, 날짜 세 부분으로 나뉘게 됩니다.
타이틀 클릭 시에는 해당 글로 이동하고, 프로필 클릭 시에는 작성자 프로필로 이동하는데 날짜 클릭 시에는 타이틀과 마찬가지로 해당 글로 이동합니다.  이는 별다른 기능이 없는데 사용자로 하여금 '혹시 날짜를 누르면 해당 날짜에 올라온 글만 볼 수 있는 기능이 있나?' 하는 착각을 불러올 수 있을 것 같았습니다.

이에 저희끼리 토론하여 날짜는 제외 하는 것이 좋겠다고 판단을 했습니다!

2022-05-02 14:33 UTC, euijinkk commented on frontend/src/components/Items/PopularStudylogItem.styles.ts
> +  transition: ease-in-out 0.1s;
그렇네요 ㅎㅎ
명시해주어야 예기치 않은 이펙트를 방지할 수 있겠습니다!
반영했습니다.

꼼꼼히 봐주셔서 감사드려요~!

2022-05-04 01:55 UTC, sunhpark42 approved these changes

2022-05-06 05:10 UTC, bigsaigon333 commented
아 이거 오늘 리뷰 남겨놓을게요~
서니가 다 해줘서 별 문제 없을거 같긴 하지만 ㅎㅎ..

2022-05-06 15:31 UTC, bigsaigon333 approved these changes
고생하셨습니다 👏 👏 👏 👏 

특별히 수정할 사항은 없는거 같아요 ! 소소한 코멘트 남겼으니 한번 확인만 해주세요 👍

2022-05-06 15:31 UTC, bigsaigon333 commented on frontend/src/components/Items/PopularStudylogItem.styles.ts
> +  }
👍 👍 👍 

```css
/* src/GlobalStyles.js */
a:hover {
  font-weight: 600;
}
```
이 속성이 정말로 유용한 것인가? 
더하는 건 쉬운데 빼는건 쉽지 않구나
그냥 필요한 곳마다 font-weight를 써주는게 더 낫지 않을까?
CSS-in-JS의 장점은 영향범위를 줄여서 관리를 용이하게 하는 것인데, 저 멀리 존재하는 GlobalStyles가 여기에 영향을 미치는게 맞는 것인가?

요런 것들도 한번쯤 생각해보셨으면 좋겠습니다 👍

2022-05-06 15:31 UTC, bigsaigon333 commented on frontend/src/pages/MainPage/styles.ts
> +  height: 36rem;
TMI) 
인기 있는 학습로그 섹션의 높이가 증가하였네요!

번거롭겠지만 사소한 변경사항이라도 공유하는 습관을 들여놓으면 좋을거 같아요 😄 

이러한 변경이 누군가에게는 굉장히 크게 다가올 수도 있거든요.
예를 들어, 같은 부분을 작업하는 다른 개발자는 높이가 증가하는 걸 모르고 다 디자인을 맞춰놨을 수도 있고,
디자이너 분들은 이런거를 맘대로 바꾸는걸 용납하지 않으시겠죠 ㅎㅎ..

그리고 피그마에 높이 변경을 반영해두지 않으면 점점 디자인 시안과 코드와의 괴리가 생겨서 어느게 맞는건지 모르는 상황이 발생할 수도 있습니다 😅

2022-05-11 23:38 UTC, merged