feat: 인기있는 학습로그를 각 카테고리 별 공통, 프론트엔드, 백엔드로 제공하는 기능 구현
woowacourse/prolog pull request #897
Opened 2022-06-06 05:09 UTC by Wishoon

### 기능 구현 전

- [x] 인기있는 학습로그를 통합으로 제공

### 기능 구현

- [x] 인기있는 학습로그를 공통, 프론트엔드, 백엔드로 제공

### Issue
https://github.com/woowacourse/prolog/issues/881

2022-06-06 07:23 UTC, gracefulBrown requested changes
현재 작성되어있는 학습로그가 어떤 코스(프론트엔드 or 백엔드)에 속해있는지 확인하기 어려울꺼에요
그래서 정규식으로 구분을 하고 있는 것 같은데 조금 더 명확하게 하면 좋을 것 같아요.

도메인 중에 MemberGroup이라는 도메인이 있을꺼에요
이 도메인으로 백엔드와 프론트엔드를 구분할 수 있어요
그래서 학습로그를 조회할 때 작성자가 어떤 MemberGroup에 속해있는지를 판단해서 
어떤 과정의 학습로그인지를 판단하면 조금 더 명확하지 않을까? 라는 생각이 들어요

확인해서 궁금한 점 있으면 다시 질문 주세요~

2022-06-06 07:23 UTC, gracefulBrown commented on backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java
> +//        assertThat(popularStudylogs.getAllResponse().getData().get(1).getId()).isEqualTo(studylogResponse2.getId());
주석은 과감히 제거해주셔도 됩니다 :)

2022-06-06 07:23 UTC, gracefulBrown commented on backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java
> +    private static final String URL = "http://localhost:8080";
이 코드의 용도는 무엇인가요?

2022-06-06 08:53 UTC, Wishoon commented on backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java
> +    private static final String URL = "http://localhost:8080";
작성되어 있는 코드라 크게 신경쓰지 않았는데 사용되지 않고 있군요 ㅎㅎ.. 제거하도록 하겠습니다 😁

2022-06-06 09:11 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/session/domain/Session.java
> +
픽스쳐에서 사용되는 메서드를 프로덕션 엔티티가 가지고 있는 이유는 무엇인가요?

2022-06-06 09:39 UTC, Wishoon commented on backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java
> +//        assertThat(popularStudylogs.getAllResponse().getData().get(1).getId()).isEqualTo(studylogResponse2.getId());
다음 커밋때 반영하겠습니다 :)

2022-06-06 23:57 UTC, Hyeon9mak commented
추가로 SonarCloud 코드 스멜도 확인해주시면 좋을거 같아요!

2022-06-09 08:11 UTC, Wishoon commented on backend/src/acceptanceTest/java/wooteco/prolog/fixtures/StudylogAcceptanceFixture.java
> +            tagRequests);
놓친 부분이네요 ㅎㅎ 수정해서 반영하겠습니다~

2022-06-09 08:19 UTC, Wishoon commented on backend/src/acceptanceTest/java/wooteco/prolog/fixtures/StudylogAcceptanceFixture.java
> +        TAG6
저도 네이밍을 이용한 픽스쳐가 명확한 전달을 해줄 것으로 생각하는데요ㅎㅎ 현재 구조가 선택된 이유는 현구막 말씀처럼 기존 픽스쳐들과 통일성을 위해서 유지를 하였습니다.

다만 다른 의견도 있었는데요 https://github.com/woowacourse/prolog/pull/875#discussion_r866529224 와 같은 리뷰를 참고해서 기존처럼 번호 하드코딩으로 하자는 의견도 있었습니다.

2022-06-09 08:28 UTC, Wishoon commented on backend/src/main/java/wooteco/prolog/session/domain/Session.java
> +
엇 저는 해당 메서드를 픽스쳐에서만 사용되지 않는다고 생각하는데요. 이 메서드를 통해서 `Seesion`이 어디 과정에 속하는지 `PopularStudylogService`에서 확인할 수 있다고 생각하고 있습니다.

2022-06-20 01:44 UTC, Hyeon9mak commented on backend/src/acceptanceTest/java/wooteco/prolog/fixtures/StudylogAcceptanceFixture.java
> +        TAG6
굿굿! 단순히 따라한게 아니라 의도를 가지고 진행하신거라면 충분하다고 생각합니다!

2022-06-20 01:58 UTC, Hyeon9mak commented on backend/src/main/java/wooteco/prolog/session/domain/Session.java
> +
오 그렇네요!! 제가 섣부르게 확인한거 같습니다 🙏 
(제 환경에서 로드가 덜 된건지, 이번에는 픽스쳐에는 안보이네요... 뭐지...)

`isSameAs` 메서드가 `PopularStudylogService`에서만 사용되는거 같은데요,
`Studylog` 엔티티에서 `Session`을 뽑아낸 다음 `isSameAs`를 호출하고 있는거 같습니다.
`Studylog` 에서 `Session` 쪽으로 메세지를 보내보면 어떨까요?

2022-06-26 02:10 UTC, Wishoon commented on backend/src/main/java/wooteco/prolog/session/domain/Session.java
> +
앗 그렇네요 ㅎㅎ.. 현구막 말씀대로 메세지를 보내는 방향으로 수정했습니다!! 

추가적으로 브라운이랑 얘기해본 결과 `Curriculum`을 사용하지 않고 기존의 클래스 중 하나인 `MemberGroup`을 활용하는 방향으로 진행하기로 했습니다~! 그래서 기존 코드가 수정이 이루어질 것으로 보입니다!!

2022-07-07 15:05 UTC, Wishoon commented
Close 후 PR 다시 올리겠습니다!

2022-07-07 15:05 UTC, closed without merging